### ISSUE TITLE
dsh-ping ttl

### ISSUE THREAD

**Issue by yverbin** [walterdejong/synctool#50]
Why this application uses the ping command with -t 1 (ttl=1) parameter ?

**Comment by walterdejong** [comment]
Probably an unfortunate clash of options. On BSD, `ping -t` is for timeout. On Linux, `ping -t` is apparently for ttl and timeout is `-w`. Maybe the docs should mention this. Personally I use `fping -t`.

**Comment by walterdejong** [comment]
changed to `-w` in commit bdbf4da
