### ISSUE TITLE
python2 end-of-life

### ISSUE THREAD

**Issue by walterdejong** [walterdejong/synctool#55]
synctool is Python 2 code. Python 2 goes end-of-life soon: https://pythonclock.org/

**Comment by walterdejong** [comment]
Python 2 should be around for a while, but it's going to end sooner rather than later. Moreover it depends heavily on what your OS or Linux/BSD distro of choice is doing. synctool has always been a very multi-platform, even platform-agnostic tool, but in any case it needs python2 to function.

**Comment by fancsali** [comment]
Just out of curiosity: is there a plan to upgrade the code to python3 eventually?

**Comment by walterdejong** [comment]
This issue is mostly here as a kind of warning sign.
Never say never, but currently there is no plan to convert to Python 3.

I have looked into this quite some time ago, and doing it right was a lot more involved than expected. synctool is a big code and then it needs to be tested too. On top of that, OS distros tend to offer rather old Python 3 versions, and it's really not helping the adoption of Python 3.

Every now and I then I get this request by email and then I get the itch again. But I think I'd sooner develop a new tool in the same vein than do a straight conversion of the current code base. Just being realistic here.

**Comment by walterdejong** [comment]
Pull request #58 by @celane will update synctool to Python 3.

**Comment by walterdejong** [comment]
Latest commits are for python3.
